title: Filestash &mdash; Self-hosted client for your data
description: "The official website for Filestash (formerly Nuage), the self-hosted web client for your data"
kramdown:
  toc_levels: "2"
url: https://www.filestash.app
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-gzip

permalink: :year/:month/:day/:title/
collections:
  docs:
    output: true

jekyll-archives:
  layout: 'post-archive'
  enabled:
    - year
    - month
    - day
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'